syntax on

set encoding=utf-8

set tabstop=2
set softtabstop=2
set shiftwidth=2
set ignorecase
set smartcase
set incsearch
set scrolloff=2
set wildmode=longest,list
set nocompatible
set autoindent
set mouse=a
set iskeyword-=_ " allow underscore to delimit words"

"draw tabs & trailing spaces
autocmd BufNewFile,BufRead * set list listchars=tab:›\ ,trail:-

"highlight any spaces that are followed by a tab (the horror!)
" and any _single_ space that comes after ^\t+ (this is usually accedental)
autocmd BufNewFile,BufRead * match Error /\( \+\t\@=\)\|\(^\(\t\+\)\zs \ze[^ ]\)/

" tab left & right
map <C-m> gt
map <C-n> gT
" home & end
map <C-l> g$
map <C-h> g^

" scroll (without moving cursor) on ctrl+j/k
map <C-k> <C-y>
map <C-j> <C-e>
map <C-t> :tabnew

" allow status-bar windows (0-height)
set wmh=0


