# NOTE: generated by niv-util; run niv-util init to regenerate
opts:
import
  (builtins.fetchurl "https://raw.githubusercontent.com/timbertson/niv-util/3b71ea06145debe7c6bf27f18e350ae690467225/default.nix")
  ({ sourcesFile = ./sources.json; } // opts)

