#!/usr/bin/env python

import os
import sys
import shutil
import subprocess

base = os.path.abspath(os.path.dirname(sys.argv[0]))
configs = ['base'] + sys.argv[1:]
print "configs: %r" % (configs,)
for config in configs:
	f = open(os.path.join(base, 'links-%s' % (config,)))

	try:
		for line in f:
			if not line.strip(): continue
			src, dest = line.rstrip().split(' ', 1)
			dest = os.path.expanduser(dest)
			src = os.path.abspath(os.path.join(base, src))
			if not os.path.exists(src):
				print "ERROR: non-existant path: %s" % (src,)
				sys.exit(1)
			print "linking %s to %s" % (src, dest)
			try:
				subprocess.check_call(['../bin/ln_i', src, dest])
			except subprocess.CalledProcessError:
				print "Trying sudo..."
				subprocess.check_call(['sudo', '../bin/ln_i', src, dest])
				print "Done."

	finally:
		f.close()

