syntax on
set number
filetype plugin on
color ir_black

set encoding=utf-8

set tabstop=2
set softtabstop=2
set shiftwidth=2
set ignorecase
set smartcase
set incsearch
set scrolloff=2
set wildmode=longest,list
set nocompatible
set autoindent
set smartindent
set mouse=a
set iskeyword-=_ " allow underscore to delimit words"

"draw tabs & trailing spaces
autocmd BufNewFile,BufRead * set list listchars=tab:›\ ,trail:-

"highlight any spaces that are followed by a tab (the horror!)
" and any _single_ space that comes after ^\t+ (this is usually accedental)
autocmd BufNewFile,BufRead * match Error /\( \+\t\@=\)\|\(^\(\t\+\)\zs \ze[^ ]\)/

" tab left & right
map <C-m> gt
map <C-n> gT

" home & end
map <C-l> g$
map <C-h> g^
" foward & back words at a time
map <S-h> b
map <S-l> w

" scroll (without moving cursor) on ctrl+j/k
map <C-k> <C-y>
map <C-j> <C-e>

" new tab with ctl+t
map <C-t> :tabnew<cr>

" allow status-bar windows (0-height)
set wmh=0

" map slash (in visual mode) to block comment toggle
vmap / ]#
" and ctl+slash to line comment toggle
map <C-/> ]#

" ctrl+f to FuzzyFinder (recursive)
map <C-f> :call g:FuzzyFinderMode.File.launch_base("**/", 0)<cr>

" copy full path to clipboard
nmap <C-c> :silent !echo -n "%:p" \| pbcopy<cr>
