#!/usr/bin/env python3
import sys, os, subprocess, shutil
dest, target = sys.argv[1:]
name = os.path.splitext(target)[0]

# only works when eveything's checked out in dev, but that's OK
root = os.path.expanduser('~/dev')

categories = os.listdir(root)
categories = list(filter(lambda dir: not dir.startswith('.'), categories))

dirs = [os.path.join(root, category, name) for category in categories]
dirs = list(filter(os.path.isdir, dirs))
if len(dirs) != 1:
	raise AssertionError("Expected exactly one %s directory, but found %s:\n%s" % (
		name,
		len(dirs),
		repr({'dirs': dirs, 'categories': categories})
	))

dir = dirs[0]
src = os.path.join(dir, 'nix', 'src.json')
subprocess.check_call(['gup', '-u', src])
shutil.copyfile(src, dest)
