# case insensitive file globbing (primaily for tab completion)
shopt -s nocaseglob
HISTCONTROL=ignoreboth

alias 'ssh-setup'='ssh_setup'
function ssh_setup
{
  if [ $(( ${SSH_AGENT_PID} + 1)) == 1 ]; then
    eval `ssh-agent`
  fi
}

