#!/bin/bash
alias ls='ls -h --color=auto' #enable colours and human-readable sizes
alias open='gnome-open'
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.bin"
export PATH="$HOME/.bin/overrides:$PATH"
