# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

autoload -Uz compinit
compinit

eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

setopt histignoredups
setopt noautomenu
WORDCHARS="${WORDCHARS:s#/#}"

# add c-x c-e to edit in vim
autoload edit-command-line
zle -N edit-command-line
bindkey '^X^e' edit-command-line

setopt autopushd

# don't export everything, that would be silly...
unsetopt ALL_EXPORT

# fix for zsh doing something weird...
# see https://bugs.launchpad.net/ubuntu/+source/zsh/+bug/355883
#bindkey ";5C" forward-word
bindkey ";3C" forward-word
bindkey "[C" forward-word
#bindkey "\e[1;5C" forward-word
#bindkey ";3C" forward-word
#bindkey ";5D" backward-word
bindkey ";3D" backward-word
bindkey "[D" backward-word
#bindkey "\e[1;5D" backward-word
#bindkey "\e[1" backward-word

# gnome-terminal keybindings:
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
bindkey "\e[3~" delete-char

# tmux seems to send these ones...
#bindkey "\e[1~" beginning-of-line
#bindkey "\e[4~" end-of-line

