#!bash -eu
root="$(dirname "$2")/root"
READLINK="readlink"
NIX_READLINK="$HOME/.nix-profile/bin/readlink"
if [ -e "$NIX_READLINK" ]; then
	READLINK="$NIX_READLINK"
fi
drv="$("$READLINK" -f "$(dirname "$2")")/envrc.drv"

cd "$root"
file="shell.nix"
if [ ! -e "$file" ]; then
	gup --ifcreate "$file"
	file="default.nix"
fi

gup -u "$file"
nix-instantiate "$file" --show-trace  --quiet --indirect --add-root "$drv" > /dev/null
nix-shell --show-trace --run "python" "$file" > "$1" <<EOF
from __future__ import print_function
import os, sys
remove_keys = []
for k in os.environ.keys():
	if k.startswith('GUP_'):
		# print("ignoring env %s" % (k,), file=sys.stderr)
		remove_keys.append(k)
for k in remove_keys:
	del os.environ[k]
os.execvp('direnv', ['direnv','dump'])
EOF

