#!bash

set -eu
export ENV_NAME='nix'
id="$(pwd | md5sum | cut -f 1 -d ' ')"
[ -n "$id" ]
base="$HOME/.config/direnv-std"
working="$base/nix-shells/$id"
mkdir -p "$working"
touch "$working"
ln -sfn "$PWD" "$working/root"
vars="$working/vars"


# set -x

# Some vars should *not* be saved to the vars dump, as they are context-dependant.
# Add these vars here, as we find them :/
ignore='DBUS_SESSION_BUS_ADDRESS NVIM_TERMINAL NVIM_LISTEN_ADDRESS XTERM COLORTERM TERM_SOLARIZED SSH_CLIENT SSH_CONNECTION SSH_TTY SSH_AUTH_SOCK'
declare -A SHADOWED_VARS

for var in $ignore; do
	value="${!var:-}"
	if [ -n "$value" ]; then
		SHADOWED_VARS[$var]="$value"
	fi
	unset "$var"
done

gup -u "$vars"

log_status "loading cached vars from $vars"
direnv_load cat "$vars"
if [ "${#SHADOWED_VARS[@]}" -ne 0 ]; then
	log_status "Restoring [${!SHADOWED_VARS[@]}]"
fi

for var in "${!SHADOWED_VARS[@]}"; do
	declare -g "$var=${SHADOWED_VARS[$var]}"
	export "$var"
done

export DIRENV_CACHE="$vars"
