#!bash
# NOTE: This is a shared config. If you want to customize it,
# make a copy first.

set -eu
export ZEROENV_NAME='nix'
id="$(pwd | md5sum | cut -f 1 -d ' ')"
[ -n "$id" ]
base="$HOME/.config/direnv-std"
working="$base/nix-shells/$id"
mkdir -p "$working"
touch "$working"
ln -sfn "$PWD" "$working/root"
vars="$working/vars"
gup -u "$vars"
log_status "loading cached vars from $vars"

# All vars are serialized in the dump, which accidentally serializes some dynamic data.
# Add such vars here, as we find them :/
ignore='DBUS_SESSION_BUS_ADDRESS NVIM_TERMINAL NVIM_LISTEN_ADDRESS XTERM COLORTERM'
for var in $ignore; do
	eval "if [ -n \"\${$var:-}\" ]; then _REAL_$var=\"\$$var\"; fi"
done

direnv_load cat "$vars"

for var in $ignore; do
	eval "if [ -n \"\${_REAL_$var:-}\" ]; then export $var=\"\$_REAL_$var\"; fi"
done
export DIRENV_CACHE="$vars"
