#!/bin/sh

alias ll='ls -l'
alias la='ls -la'
alias lt='ls -lrt'

alias diffpatch='diff -ur'
alias grep='grep --color'
alias egrep='egrep --color'
alias less='less -RSi' # raw character support; no word wrap; insensitive search
alias l='less'
alias vim.='vim ~/.bash_profile; . ~/.bash_profile'
alias ff='run firefox'
alias firefox-dev='run firefox --no-remote -p dev'
alias gd='run gnome-do'

alias g0='mkzero-gfxmonk'

alias aptinstall='sudo apt-get install'
alias aptremove='sudo apt-get remove'
alias aptsearch='apt-cache search'

alias private='ecryptfs-mount-private'

alias ad='pushd' # "add dir"
alias sd='popd'  # "subtract dir"
alias cdreal='cd `pwd -P`' # go to the canonical path, expanding all symlinks

alias ipy='ipython --noconfirm_exit'

alias ..='. ~/.bash_profile'

alias umount='sudo umount'
alias xephyr='Xephyr -ac -screen 600x800 -br -reset -terminate 2> /dev/null :1 &'

alias man='0alias --manpage --'

