#!/bin/sh

alias ll='ls -l'
alias la='ls -la'
alias lt='ls -lrt'

alias diffpatch='diff -ur'
alias grep='egrep --color'
alias less='less -RSi' # raw character support; no word wrap; insensitive search, quit-at-eof
alias l='less'
alias vim.='vim ~/.bash_profile; . ~/.bash_profile'
alias ff='firefox'

alias ad='pushd' # "add dir"
alias sd='popd'  # "subtract dir"

alias ipy='ipython --noconfirm_exit'

alias ..='. ~/.bash_profile'

alias umount='sudo umount'
