#!/bin/sh
export PATH="$PATH:/sbin:/usr/sbin"

alias 'ssh-setup'='ssh_setup'
function ssh_setup 
{
  if [ $(( ${SSH_AGENT_PID} + 1)) == 1 ]; then
    eval `ssh-agent`
  fi
}

alias tmpdir="date +'%Y-%m-%d.%H-%M-%S'"
function cdtmp {
	t=/tmp/`tmpdir`
	mkdir -p "$t" && pushd "$t"
}

function timestamp {
	while read line; do
		t=`date "+%Y-%m-%d %H:%M:%S"`
		echo "$t: $line"
	done
}