desc 'install using symlinks to this directory'
task :'link' => :nocrud do
	Dir["gfxmonk-profile/etc/profile.d/*"].each do |fl|
		destfile = fl.gsub(/^[^\/]+/,'') 
		dir = File.dirname destfile
		
		cmd "rm -rf '#{destfile}'"
		cmd "mkdir -p '#{dir}'"
		cmd "ln -s '#{Dir.pwd}/#{fl}' '#{destfile}'"
	end
end

desc 'make a .deb file'
task :deb => :nocrud do
	cmd "export COPY_EXTENDED_ATTRIBUTES_DISABLE=1 && dpkg-deb -b gfxmonk-profile"
end

task :clean do
	rm('*.deb')
end

task :nocrud do
	cmd 'find . -name \'.DS_Store\' -exec rm {} \\;'
end

def cmd(str)
	puts ">> #{str}"
	system(str) or raise("command failed!")
end

def rm(file_pattern, recursive=false, ignore_failures=false)
	Dir[file_pattern].each do |fl|
		if File.ftype(fl) == "directory"
			Dir.rmdir fl
		else
			File.delete fl
		end
	end
end