#!/bin/bash
if [ "$#" != '1' ] || [ ! -d "$1" ]; then
	echo "error: please specify the directory containing this file (bash_profile) as its first argument"
else
	base="$1"
	export PATH="$PATH:$base/bin"
	
	# colours
	RED=`tput setaf 1`
	GREEN=`tput setaf 2`
	YELLOW=`tput setaf 3`
	BLUE=`tput setaf 4`
	MAGENTA=`tput setaf 5`
	CYAN=`tput setaf 6`
	WHITE=`tput setaf 7`
	LIGHT=`tput setaf 9`
	GREY=`tput setaf 0`
	PS1='\n\[$GREY\][\T] \[$YELLOW\]\u\[$GREY\]@\[$RED\]\h \[$BLUE\]\w/\[$GREEN\] \$\[$LIGHT\] '

	function title
	{
	  export PROMPT_COMMAND='echo -ne "\033]0;'"$@"'\007"'
	  #$PROMPT_COMMAND
	}

	if [ `uname` == 'Darwin' ]; then
		source "$base/osx"
	else
		source "$base/linux"
	fi

	source "$base/scm"
	source "$base/alias"
	
	# case insensitive file globbing (primaily for tab completion)
	shopt -s nocaseglob
	
	function cdbase {
		d=`dirname "$1"`
		cd "$d"
	}
fi
