#!/bin/sh

alias giff='git diff'

# alias 'g' to git. If no args supplied, do "git status"
function g
{
	if [ "$#" = '0' ]; then
		git status
	else
		git $@
	fi
}

# make subversion diff almost as awesome as git's:
function svndiff
{
	svn diff $@ | color-diff
}
